name: Setup

description: Checkout repository & install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn

    - run: yarn install --immutable
      shell: bash
