[context.production.environment]
    REACT_APP_APPLICATION_NAME = "Talisman ◬"
    RAMP_API_KEY = "auu2eae53pvp6pboq7oft9dxh5fznhwq7h6tpaxq"

[context.staging.environment]
    REACT_APP_APPLICATION_NAME = "Talisman Staging ◬"
    RAMP_API_KEY = "y3asdf899w5xcnxguzas93uwg86dcxz54xaogyt9"
    RAMP_URL = "https://ri-widget-staging.firebaseapp.com"

[context.deploy-preview.environment]
    REACT_APP_APPLICATION_NAME = "Talisman PR Preview ◬"
    RAMP_API_KEY = "auu2eae53pvp6pboq7oft9dxh5fznhwq7h6tpaxq"
    RAMP_URL = "https://ri-widget-staging.firebaseapp.com"

