import { useInfiniteQuery } from '@tanstack/react-query'
import axios from 'axios'

import { SubnetIdentityResponse } from '../types'

const TAOSTATS_API_KEY = import.meta.env.VITE_TAOSTATS_API_KEY
const TAOSTATS_API_URL = import.meta.env.VITE_TAOSTATS_API_URL

const fetchSubnetIdentities = async ({ pageParam = 1 }) => {
  const { data } = await axios.get<SubnetIdentityResponse>(`${TAOSTATS_API_URL}/api/subnet/identity/v1`, {
    params: { page: pageParam },
    method: 'GET',
    headers: {
      Authorization: TAOSTATS_API_KEY,
      'Content-Type': 'application/json',
    },
  })
  return data
}

export function useGetInfiniteSubnetIdentities() {
  return useInfiniteQuery({
    queryKey: ['infiniteSubnetDescriptions'],
    placeholderData: {
      pages: [initialData],
      pageParams: [1],
    },
    queryFn: fetchSubnetIdentities,
    getNextPageParam: lastPage => lastPage.pagination.next_page ?? undefined,
    getPreviousPageParam: firstPage => firstPage.pagination.prev_page ?? undefined,
    initialPageParam: 1,
    staleTime: 5 * 60 * 1000, // 5 mins
    gcTime: 10 * 60 * 1000, // 10 mins
    refetchOnReconnect: true,
  })
}

export const initialData: SubnetIdentityResponse = {
  pagination: {
    current_page: 1,
    per_page: 50,
    total_items: 65,
    total_pages: 2,
    next_page: 2,
    prev_page: null,
  },
  data: [
    {
      netuid: 0,
      subnet_name: 'Root',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 1,
      subnet_name: 'Apex',
      github_repo: 'https://github.com/macrocosm-os/prompting',
      subnet_contact: 'support@macrocosmos.ai',
      subnet_url: 'https://www.macrocosmos.ai/sn1',
      discord: 'macrocrux',
      description: 'Apex intelligence',
      additional: '',
    },
    {
      netuid: 2,
      subnet_name: 'omron 🥩',
      github_repo: 'https://github.com/inference-labs-inc/omron-subnet',
      subnet_contact: '',
      subnet_url: 'https://omron.ai/',
      discord: '',
      description: 'inference and compute verification marketplace and accelerator',
      additional: '',
    },
    {
      netuid: 3,
      subnet_name: 'τemplar',
      github_repo: 'https://github.com/tplr-ai/templar',
      subnet_contact: 'info@tplr.ai',
      subnet_url: 'formalised_tensor',
      discord: '@formalised_tensor',
      description: 'www.tplr.ai',
      additional: '',
    },
    {
      netuid: 4,
      subnet_name: 'Targon',
      github_repo: 'https://github.com/manifold-inc/targon',
      subnet_contact: 'devs@manifold.inc',
      subnet_url: 'https://targon.com',
      discord: '',
      description: 'Targon is a decentalized, frontier AI lab',
      additional: '',
    },
    {
      netuid: 5,
      subnet_name: 'OpenKaito',
      github_repo: 'https://github.com/OpenKaito/openkaito',
      subnet_contact: 'webroot@kaito.ai',
      subnet_url: 'https://sn5.kaito.ai/',
      discord: '',
      description: 'Creating SOTA embedding models through decentralized incentives',
      additional: '',
    },
    {
      netuid: 6,
      subnet_name: 'Infinite Games',
      github_repo: 'https://github.com/amedeo-gigaver/infinite_games',
      subnet_contact: '',
      subnet_url: 'https://www.infinitegam.es/',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 7,
      subnet_name: 'SubVortex',
      github_repo: 'https://github.com/eclipsevortex/SubVortex',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: 'a FREE alternative to finney, just use --network subvortex',
      additional: '',
    },
    {
      netuid: 8,
      subnet_name: 'Proprietary Trading Network',
      github_repo: 'https://github.com/taoshidev/proprietary-trading-network',
      subnet_contact: '',
      subnet_url: 'https://www.taoshi.io/',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 9,
      subnet_name: 'Pretrain',
      github_repo: 'https://github.com/macrocosm-os/pretraining',
      subnet_contact: 'support@macrocosmos.ai',
      subnet_url: 'https://www.macrocosmos.ai/sn9',
      discord: 'macrocrux',
      description: 'SOTA models built by Bittensor',
      additional: '',
    },
    {
      netuid: 10,
      subnet_name: 'Sturdy',
      github_repo: 'https://github.com/Sturdy-Subnet/sturdy-subnet',
      subnet_contact: '',
      subnet_url: 'sturdysubnet.org',
      discord: '',
      description: 'Decentralized yield optimizers.',
      additional: '',
    },
    {
      netuid: 11,
      subnet_name: 'Dippy',
      github_repo: 'https://github.com/impel-intelligence/dippy-bittensor-subnet',
      subnet_contact: 'support@dippy.ai',
      subnet_url: 'https://bittensor.dippy.ai/play',
      discord: '',
      description: "Creating The World's Best Open-Source Roleplay LLM",
      additional: '',
    },
    {
      netuid: 12,
      subnet_name: 'Compute Horde',
      github_repo: 'https://github.com/backend-developers-ltd/ComputeHorde/',
      subnet_contact: '',
      subnet_url: 'https://computehorde.io',
      discord: '',
      description: 'trusted compute for bittensor validators',
      additional: '',
    },
    {
      netuid: 13,
      subnet_name: 'Data Universe',
      github_repo: 'https://github.com/macrocosm-os/data-universe',
      subnet_contact: 'support@macrocosmos.ai',
      subnet_url: 'https://www.macrocosmos.ai/sn13',
      discord: 'macrocrux',
      description: 'Web scale data scraping',
      additional: '',
    },
    {
      netuid: 14,
      subnet_name: 'Vector-Store',
      github_repo: 'https://github.com/vector-pool/vector-store',
      subnet_contact: 'rodolfobenjamim212@gmail.com',
      subnet_url: 'https://tensorpool.net/',
      discord: 'johanson.chris',
      description: '',
      additional: '',
    },
    {
      netuid: 15,
      subnet_name: 'de_val',
      github_repo: 'https://github.com/deval-core/De-Val',
      subnet_contact: 'info@de-val.ai',
      subnet_url: 'www.de-val.ai',
      discord: '',
      description: 'Developing open-source Evaluation models for generative AI',
      additional:
        'We help you identify critical issues in generative AI outputs before deploying to end users, ensuring better AI performance from the get go.',
    },
    {
      netuid: 16,
      subnet_name: 'BitAds',
      github_repo: 'https://github.com/eseckft/BitAds.ai',
      subnet_contact: '',
      subnet_url: 'https://bitads.ai/',
      discord: 'eseck',
      description: 'Revolutionizing the online marketing landscape through the power of decentralization.',
      additional: '',
    },
    {
      netuid: 17,
      subnet_name: '404—GEN',
      github_repo: 'https://github.com/404-Repo/three-gen-subnet',
      subnet_contact: '404@404.xyz',
      subnet_url: 'https://404.xyz/',
      discord: '404gen',
      description: 'democratizing 3D content creation with AI generated virtual worlds',
      additional:
        'This subnet aims to kickstart the next revolution in gaming around AI native games, ultimately leveraging the broader Bittensor ecosystem to facilitate experiences in which assets, voice and sound are all generated at runtime.',
    },
    {
      netuid: 18,
      subnet_name: 'Zeus',
      github_repo: 'https://github.com/Orpheus-AI/Zeus',
      subnet_contact: '',
      subnet_url: 'https://www.zeussubnet.com/',
      discord: '',
      description: 'Environmental Forecasting',
      additional: '',
    },
    {
      netuid: 19,
      subnet_name: 'Nineteen.ai',
      github_repo: 'https://github.com/namoray/nineteen/',
      subnet_contact: 'contact@rayonlabs.ai',
      subnet_url: 'https://nineteen.ai',
      discord: '',
      description: 'Decentralised permisonless, serverless, scalable inference',
      additional: '',
    },
    {
      netuid: 20,
      subnet_name: 'BitAgent - Rizzo',
      github_repo: 'https://github.com/RogueTensor/bitagent_subnet',
      subnet_contact: 'bitagent@rizzo.network',
      subnet_url: 'https://bitagent.rizzo.network',
      discord: 'roguetensor',
      description: "AI Agency's backbone - building the best tool-calling model",
      additional: 'MSP Tech (https://msptech.ai) and GoGoAgent (https://gogoagent.ai)',
    },
    {
      netuid: 21,
      subnet_name: 'OMEGA Any-to-Any',
      github_repo: 'https://github.com/omegalabsinc/omegalabs-anytoany-bittensor',
      subnet_contact: 'contact@omega-labs.ai',
      subnet_url: 'https://sn21.ai',
      discord: 'parshantdeep',
      description: "Making the world's first and smartest opensource any-to-any AGI system",
      additional: '',
    },
    {
      netuid: 22,
      subnet_name: 'Desearch',
      github_repo: 'https://github.com/datura-ai/desearch',
      subnet_contact: '',
      subnet_url: 'https://console.datura.ai/',
      discord: '',
      description: 'Decentralized Search',
      additional: '',
    },
    {
      netuid: 23,
      subnet_name: 'Zuvu',
      github_repo: 'https://github.com/SocialTensor/SocialTensorSubnet',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 24,
      subnet_name: 'OMEGA Labs',
      github_repo: 'https://github.com/omegalabsinc/omegalabs-bittensor-subnet',
      subnet_contact: 'contact@omega-labs.ai',
      subnet_url: 'https://focus.inc',
      discord: 'sshahid',
      description:
        'OMEGA Focus is a 1-click miner that anyone can install and start earning TAO for doing productive work, powered by Subnet 24',
      additional: '',
    },
    {
      netuid: 25,
      subnet_name: 'Folding',
      github_repo: 'https://github.com/macrocosm-os/folding',
      subnet_contact: 'support@macrocosmos.ai',
      subnet_url: 'https://www.macrocosmos.ai/sn25',
      discord: 'macrocrux',
      description: 'Protein folding and drug discovery',
      additional: '',
    },
    {
      netuid: 26,
      subnet_name: 'Storb',
      github_repo: 'https://github.com/fr34kcoders/storb-rs',
      subnet_contact: 'storbdevs@gmail.com',
      subnet_url: 'https://storb.dev',
      discord: 'shr1ftyy',
      description: 'An object storage subnet on the Bittensor network',
      additional: '',
    },
    {
      netuid: 27,
      subnet_name: 'NI Compute',
      github_repo: 'https://github.com/neuralinternet/compute-subnet',
      subnet_contact: 'neuralinternet@gmail.com',
      subnet_url: 'https://neuralinternet.ai/',
      discord: 'https://discord.com/invite/neuralinternet',
      description: 'Transforming AI compute power into a digital commodity',
      additional: '$NI',
    },
    {
      netuid: 28,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 29,
      subnet_name: 'Coldint',
      github_repo: 'https://github.com/coldint/coldint_validator',
      subnet_contact: '',
      subnet_url: 'https://coldint.io',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 30,
      subnet_name: 'Bettensor',
      github_repo: 'https://github.com/Nickel5-Inc/bettensor',
      subnet_contact: 'bettensor30@gmail.com',
      subnet_url: 'https://www.bettensor.com',
      discord: 'prediction_addiction',
      description: 'Global sports prediction on Bittensor.',
      additional: 'More sports added frequently.',
    },
    {
      netuid: 31,
      subnet_name: 'NASChain',
      github_repo: 'https://github.com/neuronlogic/NASChain',
      subnet_contact: '',
      subnet_url: 'https://dashboard.naschain.ai/leader-board',
      discord: '',
      description: 'Distributed Neural Architecture Search (NAS) on Bittensor',
      additional: '',
    },
    {
      netuid: 32,
      subnet_name: 'ItsAI',
      github_repo: 'https://github.com/It-s-AI/llm-detection',
      subnet_contact: 'help@its-ai.org',
      subnet_url: 'its-ai.org',
      discord: 'sergak0',
      description: 'AI Detector: Bittensor & decentralised AI - top performance.',
      additional: 'We detect AI by levering Bittensor solution.',
    },
    {
      netuid: 33,
      subnet_name: 'ReadyAI',
      github_repo: 'https://github.com/afterpartyai/bittensor-conversation-genome-project',
      subnet_contact: 'david@readyai.ai',
      subnet_url: 'https://readyai.ai',
      discord: 'davfields',
      description: 'Structured Data Processing at Scale for AI Models',
      additional: '',
    },
    {
      netuid: 34,
      subnet_name: 'BitMind',
      github_repo: 'https://github.com/BitMind-AI/bitmind-subnet',
      subnet_contact: 'intern@bitmind.ai',
      subnet_url: 'https://bitmind.ai',
      discord: 'kenobijon',
      description: '',
      additional: 'Generalized   deep fake detection',
    },
    {
      netuid: 35,
      subnet_name: 'LogicNet',
      github_repo: 'https://github.com/LogicNet-Subnet/LogicNet',
      subnet_contact: 'hung.le@aitprotocol.ai',
      subnet_url: 'https://logicnet.ai/',
      discord: '_tonyle',
      description: 'Think BIGGER, with smaller models',
      additional: '',
    },
    {
      netuid: 36,
      subnet_name: 'web-agents',
      github_repo: 'https://github.com/autoppia/autoppia_web_agents_subnet',
      subnet_contact: '',
      subnet_url: 'autoppia.com',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 37,
      subnet_name: 'Finetuning',
      github_repo: 'https://github.com/macrocosm-os/finetuning',
      subnet_contact: 'support@macrocosmos.ai',
      subnet_url: 'https://www.macrocosmos.ai/sn37',
      discord: 'macrocrux',
      description: 'SOTA models built by Bittensor',
      additional: '',
    },
    {
      netuid: 38,
      subnet_name: 'Distributed Training',
      github_repo: 'https://github.com/KMFODA/DistributedTraining',
      subnet_contact: '',
      subnet_url: '',
      discord: 'kmfoda',
      description: 'Trustless Decentralised Distributed Training',
      additional: 'Incentivizing model loss reduction and honest fast state sharing',
    },
    {
      netuid: 39,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 40,
      subnet_name: 'Chunking',
      github_repo: 'https://github.com/VectorChat/chunking_subnet',
      subnet_contact: '',
      subnet_url: 'https://subnet.chunking.com',
      discord: '',
      description: 'Incentivizing the best text segmentation models',
      additional: '',
    },
    {
      netuid: 41,
      subnet_name: 'SPORTSTENSOR',
      github_repo: 'https://github.com/sportstensor/sportstensor',
      subnet_contact: 'sportstensor@gmail.com',
      subnet_url: 'https://www.sportstensor.com/',
      discord: '',
      description: 'Incentivized sports predictions beating the market.',
      additional: '',
    },
    {
      netuid: 42,
      subnet_name: 'Real-Time Data by Masa',
      github_repo: 'https://github.com/masa-finance/masa-bittensor',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: 'Real-time, structured, and high-quality data for AI Applications.',
      additional: '',
    },
    {
      netuid: 43,
      subnet_name: 'Graphite',
      github_repo: 'https://github.com/GraphiteAI/Graphite-Subnet',
      subnet_contact: 'team@graphite-ai.net',
      subnet_url: 'https://graphite-ai.net/',
      discord: 'sherwin.graphite',
      description: 'Delivering state-of-the-art graph solutions',
      additional: '',
    },
    {
      netuid: 44,
      subnet_name: 'Score',
      github_repo: 'https://github.com/score-technologies/score-vision',
      subnet_contact: 'hello@wearescore.com',
      subnet_url: 'https://www.scorevision.io/',
      discord: '',
      description: 'Computer vision for sports insights and predictions.',
      additional: '',
    },
    {
      netuid: 45,
      subnet_name: 'SWE - Rizzo',
      github_repo: 'https://github.com/brokespace/code',
      subnet_contact: 'swe@rizzo.network',
      subnet_url: 'https://swe.rizzo.network',
      discord: 'brokespace',
      description: "The Everyman's Coding Platform - building the best AI SWE",
      additional: 'Free Code Completion for your editor - Gen42 (https://gen42.ai)',
    },
    {
      netuid: 46,
      subnet_name: 'Neural3D',
      github_repo: 'https://github.com/goneuralai/neural-subnet',
      subnet_contact: 'support@goneural.ai',
      subnet_url: 'https://goneural.ai/',
      discord: '@neutanent',
      description: 'Neural3D is generating 3D assets for gaming and virtual exp.',
      additional: '',
    },
    {
      netuid: 47,
      subnet_name: 'Condenses.ai',
      github_repo: 'https://github.com/condenses/neural-condense-subnet',
      subnet_contact: 'info@condenses.ai',
      subnet_url: 'https://www.condenses.ai/',
      discord: '',
      description: 'Accelerating LLM inference by text-to-text compression',
      additional: '',
    },
    {
      netuid: 48,
      subnet_name: 'NextPlace',
      github_repo: 'https://github.com/Nickel5-Inc/Nextplace',
      subnet_contact: 'operations@nickel5.com',
      subnet_url: 'https://nextplace.ai',
      discord: 'estatecat',
      description: 'The real estate valuation prediction subnet on B Bittensor.',
      additional: '',
    },
    {
      netuid: 49,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 50,
      subnet_name: 'Synth',
      github_repo: 'https://github.com/mode-network/synth-subnet',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 51,
      subnet_name: 'Celium',
      github_repo: 'https://github.com/Datura-ai/compute-subnet',
      subnet_contact: '',
      subnet_url: 'https://celiumcompute.ai/',
      discord: '',
      description: 'Decentralized, Efficient Compute Marketplace',
      additional: '',
    },
    {
      netuid: 52,
      subnet_name: 'Dojo',
      github_repo: 'https://github.com/tensorplex-labs/dojo',
      subnet_contact: 'jarvis@tensorplex.ai',
      subnet_url: 'https://dojo.tensorplex.ai',
      discord: 'https://discord.com/channels/799672011265015819/1213131262483628102',
      description: 'Premier Infrastructure Layer for Human Intelligence',
      additional: '~',
    },
    {
      netuid: 53,
      subnet_name: 'EfficientFrontier',
      github_repo: 'https://github.com/EfficientFrontier-SignalPlus/EfficientFrontier',
      subnet_contact: '',
      subnet_url: 'https://t.signalplus.com/mining',
      discord: '',
      description: 'Revolutionizing Crypto Trading with Decentralized AI',
      additional: '',
    },
    {
      netuid: 54,
      subnet_name: 'WebGenieAI',
      github_repo: 'https://github.com/web-genie-ai/web-genie-ai',
      subnet_contact: 'sangar@webgenieai.co',
      subnet_url: 'https://webgenieai.co',
      discord: 'sangar1028_72796',
      description: 'Transform text prompts/sketches/images into websites using AI',
      additional: 'https://x.com/WebGenieAiX',
    },
    {
      netuid: 55,
      subnet_name: 'Precog',
      github_repo: 'http://github.com/coinmetrics/precog',
      subnet_contact: 'precog@coinmetrics.io',
      subnet_url: 'https://precog.coinmetrics.io/',
      discord: 'uriel_coinmetrics',
      description:
        '0x507265636f6720697320616e2041492d706f776572656420686967682d6672657175656e6379202442544320707269636520666f726563617374696e67207375626e657420756e64657270696e6e656420627920436f696e204d657472696373e2809920636f6d70726568656e73697665207472757374656420646174612e204d696e6572732070726f647563652066696e616e6369616c20696e74656c6c6967656e6365207574696c697a696e672074686520646174617365747320776869636820706f77657220746865206d6f73742070726573746967696f757320696e737469747574696f6e7320746f756368696e672063727970746f',
      additional: 'X: @CM_Precog',
    },
    {
      netuid: 56,
      subnet_name: 'Gradients',
      github_repo: 'https://github.com/rayonlabs/G.O.D',
      subnet_contact: 'namoray@rayonlabs.ai',
      subnet_url: 'gradients.io',
      discord: '',
      description: 'The best 0 click training platform in the world',
      additional: '',
    },
    {
      netuid: 57,
      subnet_name: 'Gaia',
      github_repo: 'https://github.com/Nickel5-Inc/Gaia',
      subnet_contact: 'gaiaresearchnickel5@gmail.com',
      subnet_url: 'https://gaiaresearch.ai',
      discord: 'gaia_nickel5',
      description: 'A mixture-of-experts platform for geospatial data analysis on Bittensor.',
      additional: 'iCurrent tasks include weather, soil moisture and geomagnetic storms.',
    },
    {
      netuid: 58,
      subnet_name: 'Dippy Speech',
      github_repo: 'https://github.com/impel-intelligence/dippy-speech-subnet/tree/main',
      subnet_contact: 'support@dippy.ai',
      subnet_url: 'https://www.dippyspeech.com',
      discord: '',
      description: 'Best Open-Source Speech Model',
      additional: '',
    },
    {
      netuid: 59,
      subnet_name: 'Agent Arena by Masa',
      github_repo: '',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: 'The first competitive agent ecosystem on Bittensor.',
      additional: '',
    },
    {
      netuid: 60,
      subnet_name: 'Bitsec.ai',
      github_repo: 'https://github.com/Bitsec-AI/subnet',
      subnet_contact: 'john@bitsec.ai',
      subnet_url: 'https://bitsec.ai',
      discord: '~',
      description: 'AI-powered tools to find and fix software exploits',
      additional: '~',
    },
    {
      netuid: 61,
      subnet_name: 'RedTeam',
      github_repo: 'https://github.com/RedTeamSubnet/RedTeam',
      subnet_contact: 'oscar@theredteam.io',
      subnet_url: 'https://www.theredteam.io/',
      discord: 'https://discord.com/channels/799672011265015819/1319313447435108413',
      description:
        'The RedTeam subnet by Innerworks is a decentralized platform designed to drive innovation in cybersecurity through competitive programming challenges. The subnet incentivizes miners to develop and submit code solutions to various technical challenges, with a focus on enhancing security. These solutions can be integrated into real-world products to improve their security features.',
      additional: '',
    },
    {
      netuid: 62,
      subnet_name: 'Agentao',
      github_repo: 'https://github.com/taoagents/agentao',
      subnet_contact: '-',
      subnet_url: 'https://taoagents.ai/',
      discord: '-',
      description: 'The next generation of AI agents',
      additional: '-',
    },
    {
      netuid: 63,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 64,
      subnet_name: 'Chutes',
      github_repo: 'https://github.com/rayonlabs/chutes',
      subnet_contact: 'jon@chutes.ai',
      subnet_url: 'chutes.ai',
      discord: '',
      description: 'Serverless AI compute',
      additional: '',
    },
    {
      netuid: 65,
      subnet_name: 'Tensor Private Network (TPN)',
      github_repo: '',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 66,
      subnet_name: 'FakeNews',
      github_repo: 'https://github.com/gutenberg-team/fakenews-subnet',
      subnet_contact: '',
      subnet_url: 'https://taostats.io/subnets/66/chart',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 67,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 68,
      subnet_name: 'NOVA',
      github_repo: 'https://github.com/metanova-labs/nova/',
      subnet_contact: '',
      subnet_url: 'https://www.metanova-labs.com/',
      discord: '',
      description: 'Accelerating drug discovery',
      additional: '',
    },
    {
      netuid: 69,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 70,
      subnet_name: 'Vericore',
      github_repo: 'https://github.com/dfusionai/Vericore',
      subnet_contact: 'tao@dfusion.ai',
      subnet_url: 'https://www.vericore.dfusion.ai/',
      discord: 'https://discord.com/channels/799672011265015819/1349119225868058644',
      description: 'Semantic intelligence for fact-checking at scale',
      additional: '',
    },
    {
      netuid: 71,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 72,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 73,
      subnet_name: 'f(x)InTegral',
      github_repo: '',
      subnet_contact: 'lsof@proton.me',
      subnet_url: '',
      discord: 'fivebytes',
      description: '*reserved*',
      additional: 'believe',
    },
    {
      netuid: 74,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 75,
      subnet_name: 'Hippius',
      github_repo: 'https://github.com/thenervelab/thebrain',
      subnet_contact: '',
      subnet_url: 'https://hippius.com',
      discord: 'qcfUrfxuNg',
      description: 'Transparent, Decentralized, Anonymous Cloud Storage',
      additional: 'backed by a blockchain for unmatched transparency and trust.',
    },
    {
      netuid: 76,
      subnet_name: 'Safe Scan',
      github_repo: 'https://github.com/safe-scan-ai/cancer-ai',
      subnet_contact: '@ wojtasy @mr_qnd @konrad_06239',
      subnet_url: 'https://safe-scan.ai/',
      discord: 'https://discord.gg/PZevpMJrfW',
      description: 'Empowering Early Cancer Detection with Decentralized AI ',
      additional: '-',
    },
    {
      netuid: 77,
      subnet_name: 'RESERVED',
      github_repo: 'https://github.com/creativebuilds/sn77',
      subnet_contact: '',
      subnet_url: '',
      discord: 'CreativeBuilds',
      description: 'Reserved for a future subnet idea.',
      additional: 'For subnet purchase inquires contact me on X: CreativeBuilds',
    },
    {
      netuid: 78,
      subnet_name: 'Unknown',
      github_repo: null,
      subnet_contact: null,
      subnet_url: null,
      discord: null,
      description: null,
      additional: null,
    },
    {
      netuid: 79,
      subnet_name: 'τaos',
      github_repo: '',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: 'Simulation of Automated Trading in Intelligent Markets',
      additional: 'Risk-Averse AI Agent Optimization',
    },
    {
      netuid: 80,
      subnet_name: 'AI Factory',
      github_repo: 'https://github.com/star145s/ai_factory',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: '',
      additional: '',
    },
    {
      netuid: 81,
      subnet_name: 'Patrol (TAO.com)',
      github_repo: '',
      subnet_contact: '',
      subnet_url: '',
      discord: '',
      description: 'Building a decentralized Palantir for TAO.com',
      additional: '',
    },
  ],
}
