name: Load environment variables

description: Load environment variables from GitHub Action secrets & GitHub Action variables

inputs:
  secrets:
    description: Github Action secrets object
    required: false
  vars:
    description: Github Action vars object
    required: false
  environmentVariableSecrets:
    description: Github Action secrets
    required: false
  environmentVariableVariables:
    description: Github Action variables
    required: false
  environmentVariablePrefix:
    description: Environment variables prefix
    required: false

runs:
  using: composite
  steps:
    - if: inputs.environmentVariableSecrets != ''
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ inputs.secrets }}
        include: ${{ inputs.environmentVariableSecrets }}
        prefix: ${{ inputs.environmentVariablePrefix }}

    - if: inputs.environmentVariableVariables != ''
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ inputs.vars }}
        include: ${{ inputs.environmentVariableVariables }}
        prefix: ${{ inputs.environmentVariablePrefix }}
