name: Applications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    uses: ./.github/workflows/qa.yml

  deploy-ui-storybook:
    needs: [qa]
    uses: ./.github/workflows/cloudflare-pages.yml
    with:
      projectName: ${{ vars.UI_PROJECT_NAME }}
      buildCommand: yarn turbo run build-storybook --filter=ui
      outputDirectory: packages/ui/storybook-static
    secrets: inherit

  deploy-portal-storybook:
    needs: [qa]
    uses: ./.github/workflows/cloudflare-pages.yml
    with:
      projectName: ${{ vars.PORTAL_STORYBOOK_PROJECT_NAME }}
      buildCommand: yarn turbo run build-storybook --filter=web
      outputDirectory: apps/web/storybook-static
    secrets: inherit

  deploy-portal:
    needs: [qa]
    uses: ./.github/workflows/cloudflare-pages.yml
    with:
      projectName: ${{ vars.PORTAL_PROJECT_NAME }}
      buildCommand: yarn turbo run build --filter=web
      outputDirectory: apps/web/build
      environmentVariableSecrets: >-
        APPLICATION_NAME,
        ONFINALITY_API_KEY,
        SENTRY_DSN,
        POSTHOG_AUTH_TOKEN,
        TX_HISTORY_INDEXER,
        BASEROW_EXPLORE_AUTH,
        BASEROW_CROWDLOANS_AUTH
      environmentVariablePrefix: REACT_APP_
    secrets: inherit
