name: Applications

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    secrets: inherit

  deploy-portal:
    uses: ./.github/workflows/deploy.yml
    with:
      projectName: ${{ vars.PORTAL_PROJECT_NAME }}
      buildCommand: >-
        NODE_OPTIONS=--max_old_space_size=10240
        VITE_SENTRY_RELEASE=${{ github.sha }}
        yarn turbo run build --filter=portal -- --sourcemap
      outputDirectory: apps/portal/build
      sentryReleaseVersion: ${{ github.sha }}
    secrets: inherit
