name: Deploy Cloudflare Pages

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      buildCommand:
        required: true
        type: string
      environmentVariableSecrets:
        type: string
      environmentVariablePrefix:
        type: string
      outputDirectory:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.projectName }} (${{ fromJSON('["Preview", "Production"]')[github.ref_name == github.event.repository.default_branch] }})

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - if: ${{ inputs.environmentVariableSecrets != '' }}
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          include: ${{ inputs.environmentVariableSecrets }}
          prefix: ${{ inputs.environmentVariablePrefix }}

      - run: ${{ inputs.buildCommand }}

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ inputs.projectName }}
          directory: ${{ inputs.outputDirectory }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
