name: Build & deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      buildCommand:
        required: true
        type: string
      outputDirectory:
        required: true
        type: string
      sentryReleaseVersion:
        type: string
        default: ${{ github.sha }}
      environmentVariableSecrets:
        type: string
      environmentVariableVariables:
        type: string
      environmentVariablePrefix:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.projectName }} (${{ fromJSON('["Preview", "Production"]')[github.ref_name == github.event.repository.default_branch] }})

    permissions:
      actions: read
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/load-environment-variables
        with:
          secrets: ${{ toJson(secrets) }}
          vars: ${{ toJson(vars) }}
          environmentVariableSecrets: ${{ inputs.environmentVariableSecrets }}
          environmentVariableVariables: ${{ inputs.environmentVariableVariables }}
          environmentVariablePrefix: ${{ inputs.environmentVariablePrefix }}

      - run: ${{ inputs.buildCommand }}

      - uses: cloudflare/pages-action@v1
        with:
          # Explicit branch name needed because of: https://github.com/cloudflare/pages-action/issues/97
          branch: ${{ github.head_ref || github.ref_name }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ inputs.projectName }}
          directory: ${{ inputs.outputDirectory }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - if: vars.SENTRY_PROJECT != null
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: ${{ fromJSON('["preview", "production"]')[github.ref_name == github.event.repository.default_branch] }}
          version: ${{ inputs.sentryReleaseVersion }}
          sourcemaps: ${{ inputs.outputDirectory }}
