name: Build & deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      buildCommand:
        required: true
        type: string
      outputDirectory:
        required: true
        type: string
      sentryReleaseVersion:
        type: string
        default: ${{ github.sha }}
      environmentVariableSecrets:
        type: string
      environmentVariableVariables:
        type: string
      environmentVariablePrefix:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.projectName }} (${{ fromJSON('["Preview", "Production"]')[github.ref_name == github.event.repository.default_branch] }})

    permissions:
      actions: read
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      # this will inject all github secrets and variables as environment variables
      - name: Set environment variables
        shell: bash
        run: |
          # Export secrets one by one
          for secret in $(echo '${{ toJSON(secrets) }}' | jq -r 'keys[]'); do
            value=$(echo '${{ toJSON(secrets) }}' | jq -r --arg key "$secret" '.[$key]')
            echo "$secret=$value" >> $GITHUB_ENV
          done

          # Export variables one by one
          for var in $(echo '${{ toJSON(vars) }}' | jq -r 'keys[]'); do
            value=$(echo '${{ toJSON(vars) }}' | jq -r --arg key "$var" '.[$key]')
            echo "$var=$value" >> $GITHUB_ENV
          done

      - run: ${{ inputs.buildCommand }}

      - uses: cloudflare/pages-action@v1
        with:
          # Explicit branch name needed because of: https://github.com/cloudflare/pages-action/issues/97
          branch: ${{ github.head_ref || github.ref_name }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ inputs.projectName }}
          directory: ${{ inputs.outputDirectory }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - if: vars.SENTRY_PROJECT != null
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: ${{ fromJSON('["preview", "production"]')[github.ref_name == github.event.repository.default_branch] }}
          version: ${{ inputs.sentryReleaseVersion }}
          sourcemaps: ${{ inputs.outputDirectory }}
