name: Prettier

on:
  pull_request:
    branches: [prod]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: Format code
        uses: DukeManh/scoped-actions@v1
        with:
          files: ${{ steps.files.outputs.added_modified }}
          s0: 'yarn'
          s1: 'yarn run prettier --write --no-error-on-unmatched-pattern'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: prettier format'
          branch: ${{ github.head_ref }}
