name: Prettier

on:
  pull_request:
    branches: [prod]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get changed files
        id: files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          format: 'space-delimited'
          filter: |
            **.ts
            **.tsx
            **.js
            **.jsx
            **.html
            **.css
            **.scss
            !.github/**

      - name: Format code
        uses: DukeManh/scoped-actions@v1
        with:
          files: ${{ steps.files.outputs.added_modified }}
          s0: >
            yarn
          s1: >
            bash -c "[[ -n '${{ steps.files.outputs.added_modified }}' ]] && yarn run ci:formatter ${{ steps.files.outputs.added_modified }} || echo 'No files to format'"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: prettier format'
          branch: ${{ github.head_ref }}
