name: QA

on: [workflow_call]

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn install --immutable
      - run: yarn lint -- --max-warnings=0
      - run: yarn check-types
      - run: yarn test

  e2e:
    runs-on: ubuntu-latest

    environment: ${{ vars.PORTAL_PROJECT_NAME }} (${{ fromJSON('["Preview", "Production"]')[github.ref_name == github.event.repository.default_branch] }})

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      # this will inject all github secrets and variables as environment variables
      - name: Set environment variables
        shell: bash
        run: |
          # Export secrets one by one
          for secret in $(echo '${{ toJSON(secrets) }}' | jq -r 'keys[]'); do
            value=$(echo '${{ toJSON(secrets) }}' | jq -r --arg key "$secret" '.[$key]')
            echo "$secret=$value" >> $GITHUB_ENV
          done

          # Export variables one by one
          for var in $(echo '${{ toJSON(vars) }}' | jq -r 'keys[]'); do
            value=$(echo '${{ toJSON(vars) }}' | jq -r --arg key "$var" '.[$key]')
            echo "$var=$value" >> $GITHUB_ENV
          done

      - uses: ./.github/actions/setup
      - run: npx playwright install --with-deps
      - run: yarn e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: portal-playwright-report
          path: apps/portal/test-results
          if-no-files-found: ignore
