name: QA

on: [workflow_call]

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn install --immutable
      - run: yarn prettier --check .
      - run: yarn lint -- --max-warnings=0
      - run: yarn check-types
      - run: yarn test

  e2e:
    runs-on: ubuntu-latest

    environment: ${{ vars.PORTAL_PROJECT_NAME }} (${{ fromJSON('["Preview", "Production"]')[github.ref_name == github.event.repository.default_branch] }})

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/load-environment-variables
        with:
          secrets: ${{ toJson(secrets) }}
          vars: ${{ toJson(vars) }}
          environmentVariableSecrets: >-
            CHAINDATA,
            COIN_GECKO_API,
            ONFINALITY_API_KEY,
            SENTRY_DSN,
            POSTHOG_AUTH_TOKEN,
            EX_HISTORY_INDEXER,
            DOT_CROWDLOAN_INDEXER,
            KSM_CROWDLOAN_INDEXER,
            BASEROW_EXPLORE_AUTH,
            BASEROW_CROWDLOANS_AUTH,
            LIDO_REWARDS_ADDRESS
          environmentVariableVariables: >-
            APPLICATION_NAME
          environmentVariablePrefix: REACT_APP_

      - uses: ./.github/actions/setup
      - run: npx playwright install --with-deps
      - run: yarn e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: portal-playwright-report
          path: apps/web/test-results
          if-no-files-found: ignore
