name: Create Sentry release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environmentType:
        required: true
        type: string
      version:
        type: string
        default: ${{ github.sha }}
      artifactName:
        required: true
        type: string
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  create-sentry-release:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    permissions:
      actions: read

    steps:
      - uses: actions/checkout@v3

      - id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}

      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.environmentType }}
          version: ${{ inputs.version }}
          sourcemaps: ${{ steps.download.outputs.download-path }}
